services:
  - type: static
    name: literate-disco-front
    env: node
    plan: free
    branch: main
    repo: https://github.com/yogatypic/literate-disco
    rootDir: .
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    envVars:
      - key: VITE_API_URL
        value: "https://prompt-ultime-node-api.onrender.com"

  - type: web
    name: prompt-ultime-node-api
    env: node
    plan: free
    branch: main
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production

