services:
  - type: web
    name: prompt-ultime
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    branch: main
    envVars:
      - key: NODE_ENV
        value: production

